package com.codeops.controller;

import com.codeops.entity.enums.AgentType;
import com.codeops.service.ReportStorageService;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 * REST controller for report and specification file upload and download operations.
 *
 * <p>Handles storage of agent-generated markdown reports, job summary reports,
 * and specification files (PDF, images, JSON, etc.) associated with analysis jobs.
 * Files are stored in S3 (or local filesystem in dev mode). All endpoints require
 * authentication.</p>
 *
 * <p>Upload endpoints validate file size (max 50 MB) and content type against
 * an allow-list. Download endpoints validate S3 keys against path traversal
 * and format rules before delegating to storage.</p>
 *
 * @see ReportStorageService
 */
@RestController
@RequestMapping("/api/v1/reports")
@RequiredArgsConstructor
@Tag(name = "Reports")
public class ReportController {

    private static final Logger log = LoggerFactory.getLogger(ReportController.class);

    private final ReportStorageService reportStorageService;

    private static final Pattern SAFE_S3_KEY = Pattern.compile("^[a-zA-Z0-9/_\\-\\.]+$");
    private static final Set<String> ALLOWED_CONTENT_TYPES = Set.of(
            "application/pdf", "text/plain", "text/markdown", "text/csv",
            "application/json", "application/xml", "text/xml",
            "image/png", "image/jpeg", "image/gif");
    private static final long MAX_UPLOAD_SIZE = 50 * 1024 * 1024; // 50 MB

    private void validateS3Key(String s3Key) {
        if (s3Key == null || s3Key.isBlank()) {
            throw new IllegalArgumentException("S3 key is required");
        }
        if (s3Key.contains("..") || s3Key.startsWith("/")) {
            throw new IllegalArgumentException("Invalid S3 key: path traversal detected");
        }
        if (!SAFE_S3_KEY.matcher(s3Key).matches()) {
            throw new IllegalArgumentException("Invalid S3 key format");
        }
    }

    /**
     * Uploads a markdown report generated by a specific agent for an analysis job.
     *
     * <p>POST /api/v1/reports/job/{jobId}/agent/{agentType}</p>
     *
     * <p>Requires authentication. The report is stored keyed by job ID and agent type.</p>
     *
     * @param jobId           the UUID of the job the report belongs to
     * @param agentType       the type of agent that generated the report
     * @param markdownContent the raw markdown content of the report
     * @return a map containing the S3 key of the stored report with HTTP 201 status
     */
    @PostMapping("/job/{jobId}/agent/{agentType}")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<Map<String, String>> uploadAgentReport(
            @PathVariable UUID jobId,
            @PathVariable AgentType agentType,
            @RequestBody String markdownContent) {
        log.debug("uploadAgentReport called with jobId={}, agentType={}", jobId, agentType);
        String key = reportStorageService.uploadReport(jobId, agentType, markdownContent);
        return ResponseEntity.status(201).body(Map.of("s3Key", key));
    }

    /**
     * Uploads a summary report for an analysis job.
     *
     * <p>POST /api/v1/reports/job/{jobId}/summary</p>
     *
     * <p>Requires authentication. The summary report consolidates findings
     * from all agents for the given job.</p>
     *
     * @param jobId           the UUID of the job the summary belongs to
     * @param markdownContent the raw markdown content of the summary report
     * @return a map containing the S3 key of the stored summary with HTTP 201 status
     */
    @PostMapping("/job/{jobId}/summary")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<Map<String, String>> uploadSummaryReport(
            @PathVariable UUID jobId,
            @RequestBody String markdownContent) {
        log.debug("uploadSummaryReport called with jobId={}", jobId);
        String key = reportStorageService.uploadSummaryReport(jobId, markdownContent);
        return ResponseEntity.status(201).body(Map.of("s3Key", key));
    }

    /**
     * Downloads a previously uploaded markdown report by its S3 key.
     *
     * <p>GET /api/v1/reports/download?s3Key={s3Key}</p>
     *
     * <p>Requires authentication. The S3 key is validated for path traversal
     * and format safety before retrieval. Returns content with {@code text/markdown}
     * media type.</p>
     *
     * @param s3Key the S3 storage key of the report to download
     * @return the markdown content of the report
     * @throws IllegalArgumentException if the S3 key is null, blank, contains path
     *                                  traversal characters, or has an invalid format
     */
    @GetMapping("/download")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<String> downloadReport(@RequestParam String s3Key) {
        log.debug("downloadReport called with s3Key={}", s3Key);
        validateS3Key(s3Key);
        String content = reportStorageService.downloadReport(s3Key);
        return ResponseEntity.ok()
                .contentType(MediaType.parseMediaType("text/markdown"))
                .body(content);
    }

    /**
     * Uploads a specification file for an analysis job.
     *
     * <p>POST /api/v1/reports/job/{jobId}/spec (multipart/form-data)</p>
     *
     * <p>Requires authentication. The file is validated against a maximum size of
     * 50 MB and an allow-list of content types (PDF, plain text, markdown, CSV, JSON,
     * XML, PNG, JPEG, GIF). Path separators in the original filename are sanitized
     * before storage.</p>
     *
     * @param jobId the UUID of the job the specification belongs to
     * @param file  the multipart file to upload
     * @return a map containing the S3 key of the stored specification with HTTP 201 status
     * @throws IOException              if reading the file bytes fails
     * @throws IllegalArgumentException if the file exceeds 50 MB or has an unsupported content type
     */
    @PostMapping("/job/{jobId}/spec")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<Map<String, String>> uploadSpecification(
            @PathVariable UUID jobId,
            @RequestParam("file") MultipartFile file) throws IOException {
        log.debug("uploadSpecification called with jobId={}", jobId);
        if (file.getSize() > MAX_UPLOAD_SIZE) {
            throw new IllegalArgumentException("File too large (max 50MB)");
        }
        String contentType = file.getContentType();
        if (contentType == null || !ALLOWED_CONTENT_TYPES.contains(contentType)) {
            throw new IllegalArgumentException("Unsupported file type");
        }
        String filename = file.getOriginalFilename();
        if (filename != null) {
            filename = filename.replaceAll("[/\\\\]", "_"); // Strip path separators
        }
        String key = reportStorageService.uploadSpecification(
                jobId, filename, file.getBytes(), contentType);
        return ResponseEntity.status(201).body(Map.of("s3Key", key));
    }

    /**
     * Downloads a previously uploaded specification file by its S3 key.
     *
     * <p>GET /api/v1/reports/spec/download?s3Key={s3Key}</p>
     *
     * <p>Requires authentication. The S3 key is validated for path traversal
     * and format safety before retrieval. Returns the raw file bytes with
     * {@code application/octet-stream} media type.</p>
     *
     * @param s3Key the S3 storage key of the specification to download
     * @return the raw bytes of the specification file
     * @throws IllegalArgumentException if the S3 key is null, blank, contains path
     *                                  traversal characters, or has an invalid format
     */
    @GetMapping("/spec/download")
    @PreAuthorize("isAuthenticated()")
    public ResponseEntity<byte[]> downloadSpecification(@RequestParam String s3Key) {
        log.debug("downloadSpecification called with s3Key={}", s3Key);
        validateS3Key(s3Key);
        byte[] data = reportStorageService.downloadSpecification(s3Key);
        return ResponseEntity.ok()
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .body(data);
    }
}
